<a href="https://colab.research.google.com/github/rajutankala4442/Assignment-of-Gcc2025/blob/main/Assessment_for_29_06_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. Array Manipulation with Slicing and Indexing:

In [2]:
import numpy as np
a = np.arange(10)
print(a)
print(a[0])
print(a[-1])
print(a[1:5])
print(a[-5:])

[0 1 2 3 4 5 6 7 8 9]
0
9
[1 2 3 4]
[5 6 7 8 9]


#2. Data Type Conversion and Shape Manipulation:

In [3]:
import numpy as np
a = np.arange(10, dtype=np.float32)
print(a)
a = a.astype(np.int32)
print(a)
a = a.reshape((2, 5))
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


#3. Iterating over an Array:

In [9]:
import numpy as np
a = np.arange(10)
print(a)
for i in range(len(a)):
    a[i] = a[i] * 2
print(a)



[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


#4. Joining and Splitting Arrays:

In [13]:
import numpy as np

def main():
    # Create two NumPy arrays
    array1 = np.array([[1, 2, 3],
                       [4, 5, 6]])

    array2 = np.array([[7, 8, 9],
                       [10, 11, 12]])

    print("Array 1:")
    print(array1)
    print("Array 2:")
    print(array2)

    # Join arrays horizontally
    horizontal_join = np.hstack((array1, array2))
    print("\nJoined Horizontally:")
    print(horizontal_join)

    # Join arrays vertically
    vertical_join = np.vstack((array1, array2))
    print("\nJoined Vertically:")
    print(vertical_join)

    # Split the resulting array into subarrays
    subarrays = np.split(vertical_join, 2)
    print("\nSplit Subarrays:")
    for i, subarray in enumerate(subarrays):
        print(f"Subarray {i+1}:")
        print(subarray)

if __name__ == "__main__":
    main()


Array 1:
[[1 2 3]
 [4 5 6]]
Array 2:
[[ 7  8  9]
 [10 11 12]]

Joined Horizontally:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

Joined Vertically:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Split Subarrays:
Subarray 1:
[[1 2 3]
 [4 5 6]]
Subarray 2:
[[ 7  8  9]
 [10 11 12]]


#5. Searching, Sorting, and Filtering Arrays:

In [14]:
import numpy as np
# Create a NumPy array of integers
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# Search for the element 5 in the array
b = np.where(a == 5)
# Sort the array in ascending order
c = np.sort(a)
# Filter out the elements that are less than 5
d = a[a >= 5]
# Print the results
print(b)
print(c)
print(d)

(array([4]),)
[1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]


#6. Randomization and Universal Functions:

In [15]:
import numpy as np
a = np.random.randint(10, size=10)
# Print the array
print(a)
print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.min(a))

[6 6 1 0 4 6 7 2 5 3]
40
4.0
7
0
